// Generated by CoffeeScript 1.3.1
(function() {
  var Now, nowjs;

  nowjs = require('now');

  Now = (function() {

    Now.name = 'Now';

    function Now(app) {
      var everyone;
      everyone = nowjs.initialize(app);
      require('./now/nowGps.js').connect(everyone.now);
      require('./now/nowRcController.js').connect(everyone.now);
    }

    return Now;

  })();

  module.exports.connect = function(app) {
    return new Now(app);
  };

}).call(this);
