// Generated by CoffeeScript 1.3.1
(function() {
  var RcController;

  RcController = (function() {

    RcController.name = 'RcController';

    function RcController() {
      this.usbmaestro = require('usbmaestro');
      this.usbmaestro.connect();
      this.set(0, 0);
    }

    RcController.prototype.set = function(throttle, rudder) {
      var r;
	r = 1500 - (300 * rudder);
      this.usbmaestro.setTarget(0, r);

	var t;
	t = (throttle == 0) ? 0 : 1500 - 80 * throttle;
	this.usbmaestro.setTarget(2, t);
      return console.log("throttle: " + throttle + ", rudder: " + rudder + ", adjusted rudder: " + r);
    };

    return RcController;

  })();

  exports.createController = function() {
    return new RcController();
  };

}).call(this);
